

print:

run:
	say -v Alex 'My name is [[inpt PHON]] AY1yIY2SAX [[inpt TEXT]].'
	say -v Alex 'My name is [[inpt PHON]] AY1yIY2SAX [[inpt TEXT]].'
	say -v Samantha 'My name is [[inpt PHON]] AY1yIY2SAX [[inpt TEXT]].'
	say -v Sam 'I was born in 1989.'