# https://github.com/DHowett/go-plist

print:

LIB_NAME=go-plist
dep:
	rm -rf bluetooth
	git clone https://github.com/DHowett/go-plist

EX_BIN_FOLDERPATH=$(PWD)/_dist

ex-run:
	cd examples && go run .