
LIB_NAME=gio-example
dep:
	rm -rf $(LIB_NAME)
	git clone https://github.com/gioui/gio-example
	
fan-run:
	cd $(LIB_NAME)/x/outlay/fan && go run .

table-run:
	cd $(LIB_NAME)/x/outlay/table && go run .

grid-run:
	cd $(LIB_NAME)/x/outlay/grid && go run .